# -*- coding: utf-8 -*-
"""code_practice_week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weTGEVj9d8DxlBZBA-cjG7B2wHZ0bybH
"""

#watermellon
w=int(input())
x=w/2
if(w%2==0 and x%2==0 ):
    print("YES")
else:
    print("NO")

#way to long words
n=int(input())
arr=[]
for i in range(n):
 arr.append(str(input()))
print(" ")
for i in range(n):
 str1=arr[i]
 if(len(str1)>=10):
     count = len(str1)-2
     countstring=str(count)
     str2=str1[:1]+countstring+str1[len(str1)-1]
     print(str2)
 else:
     print(str1)